---
title: Project 1
subtitle: |
    | MSIT 423, Spring 2019
    | Due: April 27, 2:00pm
author: Jessica Qin, Yang Hong, Yunzi Zhang, Yifan Chen, Ray Liu
output: 
  pdf_document:
    number_sections: true
  html_document:
    keep_md: true
fontsize: 11pt
geometry: "left=1.2in, right=1.2in, top=1in, bottom=1in"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(car)
library(corrplot)
```
## Loading the data from the csv file
```{r}
setwd("~/Desktop/2019/NU/2019-spring/MSIT423/project1")
bike<-read.csv("bike.csv")
bike$avgbf= (bike$Limited_Business_License+bike$Retail_Food_Establishment)/2
```

```{r}
dmg <- bike[,c(3:5,8,10:13,45,47)]
cor(dmg)
plot(dmg)
library(MASS)
#tran1=cbind(log(com1.2[,c(1:6,9)]),com1.2[,7:8],com1.2[,10:11])
library(glmnet) 
lam = seq(0,300,length=101)/nrow(dmg)
x = model.matrix(trips~., dmg)
fitdmg=glmnet(x,dmg$trips, alpha=1, lambda = lam)
cv.lasso=cv.glmnet(x, dmg$trips, alpha=1, lambda = lam)
cv.lasso$lambda.min
coef(cv.lasso,s="lambda.min")
matplot(fitdmg$lambda*nrow(dmg), t(fitdmg$beta), type="l"); abline(h=0)
```
```{r}
#fit the model
fit2.1= lm(trips~ CTA_BUS_STATIONS+ CTA_TRAIN_STATIONS + BIKE_ROUTES + CAPACITY +I(MINORITY^2) + EDU +CBD + POPULATION_SQ_MILE +log(avgbf), data = dmg)
summary(fit2.1)
vif(fit2.1)
#diagnostic
library(car)
par(mfrow=c(2,2))
plot(fit2.1)
```

```{r}

#crime
crime <- bike[,c(15,16,17,22,24,31,40,43,45)]
plot(crime)
dmgcrime<- cbind(dmg[,c(1:10)], bike[,c(15,16,17,22,24,31,40,43)])
cor(dmgcrime)
```

```{r}
x2 = model.matrix(trips~., dmgcrime)
withcrime.lasso=cv.glmnet(x2, dmgcrime$trips, alpha=1, lambda = lam)
coef(withcrime.lasso, s="lambda.min")
#tran1=cbind(log(com1.2[,c(1:6,9)]),com1.2[,7:8],com1.2[,10:11])
par(mfrow=c(2,4))
hist(crime[,1])
hist(crime[,2])
hist(crime[,3])
hist(crime[,4])
hist(crime[,5])
hist(crime[,6])
hist(crime[,7])
hist(crime[,8])
```

```{r}
#find the best performance
set.seed(12345)
train = runif(nrow(dmgcrime))<.5   
fitall= lm(trips~ ASSAULT + BATTERY 
+ log(DECEPTIVE_PRACTICE) + log(ROBBERY) + log(THEFT) + log((HOMICIDE+2)*5) + sqrt(NARCOTICS)+BURGLARY+log(avgbf) 
         + CTA_BUS_STATIONS+ CTA_TRAIN_STATIONS + 
             BIKE_ROUTES + CAPACITY +I(MINORITY^2) + EDU +CBD + POPULATION_SQ_MILE
, data=dmgcrime, subset = train)
fitstepwise= step(fitall)
yhatsw = predict(fitstepwise, dmgcrime[!train,])
mean((dmgcrime$trips[!train] - yhatsw)^2)       # MSE=0.2378
summary(fitstepwise)
vif(fitstepwise)
```
```{r}
fitred= lm(trips~ 
 #    ASSAULT 
       + BATTERY 
#+ log(DECEPTIVE_PRACTICE) 
+ ROBBERY
#  +log(THEFT) 
+ log((HOMICIDE+2)*5) 
+ sqrt(NARCOTICS)
+BURGLARY
+log(avgbf) 
#+ CAPACITY +I(MINORITY^2) + EDU +CBD 
, data=dmgcrime, subset = train)
fitred
```

```{r}
#Ridge
dmgtrans=cbind(dmg[,c(1:6,8:10)],dmg[,7]^2)
dmgcrime2= cbind(crime[,1:3],log(crime[,c(4,7:8)]),log((crime[,5]+2)*5),sqrt(crime[,6]),dmgtrans[,1:10])
train2 = runif(nrow(dmgcrime2))<.5
xr = model.matrix(trips ~ ., dmgcrime2)
fit.ridge = glmnet(xr[train2,], dmgcrime2$trips[train2], alpha=0)
plot(fit.ridge, xvar="lambda")
fit.cv.rd = cv.glmnet(x[train2,], dmgcrime2$trips[train2], alpha=0) # find optimal lambda
fit.cv.rd$lambda.min        # optimal value of lambda
abline(v=log(fit.cv.rd$lambda.min))
plot(fit.cv.rd)          # plot MSE vs. log(lambda)
yhat = predict(fit.ridge, s=fit.cv.rd$lambda.min, newx=xr[!train2,])  # find yhat for best model
mean((dmgcrime2$trips[!train2] - yhat)^2)      # MSE=0.27
```

```{r}
#Lasso
fit.lasso = glmnet(xr[train2,], dmgcrime2$trips[train2], alpha=1)
plot(fit.lasso, xvar="lambda")
fit.cv.la = cv.glmnet(xr[train2,], dmgcrime2$trips[train2], alpha=1)
yhatla = predict(fit.lasso, s=fit.cv.la$lambda.min, newx=xr[!train2,])
mean((dmgcrime2$trips[!train2] - yhatla)^2)      # MSE=0.27177
summary(fit.lasso)
coef(fit.cv.la,s="lambda.min")
```
```{r}
#random forest
library(gam)
library(randomForest)
colnames(dmgcrime2)[7] <- "homocidetrans"
colnames(dmgcrime2)[8] <- "narcoticstrans"
colnames(dmgcrime2)[18] <- "combineddmgtrans"
fitrf=randomForest(trips ~ ., data=dmgcrime2, importance=T)
fitrf
```




```{r}
interaction.plot(dmgcrime$THEFT, dmgcrime$CBD, dmgcrime$trips, col=1:2)
```



```{r}

par(mfrow=c(2,2))
plot(fitstepwise)
vif(fitstepwise)
```

